workspace = { members = [ "Assignment1", "assignment2", "assignment3", "bootcamp1","project", "rectangle", "task1", "task2"] }
[package]
name = "class_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_math = "0.3.7"
